# Generated by Django 2.2.6 on 2020-10-15 20:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scientific_name', models.CharField(help_text='Enter the scientific name for this species', max_length=200)),
                ('phylum', models.CharField(blank=True, max_length=100, null=True)),
                ('family', models.CharField(blank=True, max_length=200, null=True)),
                ('genus', models.CharField(blank=True, max_length=200, null=True)),
                ('subgenus', models.CharField(blank=True, max_length=200, null=True)),
                ('specific_epithet', models.CharField(blank=True, max_length=200, null=True)),
                ('origin', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SpeciesInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this specimen', primary_key=True, serialize=False)),
                ('acquisition_method', models.CharField(choices=[('s', 'Seed'), ('c', 'Cutting'), ('d', 'Division'), ('a', 'Acquired')], default='s', max_length=1)),
                ('date_acquired', models.DateField(blank=True, help_text='Date acquired, or date sown if from seed.', null=True)),
                ('imprint', models.CharField(max_length=200)),
                ('species', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogue.Species')),
            ],
            options={
                'ordering': ['date_acquired'],
            },
        ),
        migrations.CreateModel(
            name='SpeciesDescriptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=4000)),
                ('descript_type', models.CharField(max_length=100)),
                ('species', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogue.Species')),
            ],
        ),
        migrations.CreateModel(
            name='CommonNames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_name', models.CharField(max_length=200)),
                ('meaning', models.CharField(max_length=500)),
                ('species', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogue.Species')),
            ],
        ),
    ]
