# Generated by Django 2.2.6 on 2020-10-15 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CommonNames',
            new_name='CommonName',
        ),
        migrations.RenameModel(
            old_name='SpeciesDescriptions',
            new_name='SpeciesDescription',
        ),
        migrations.AlterModelOptions(
            name='species',
            options={'verbose_name_plural': 'Species'},
        ),
    ]
