# Generated by Django 2.2.6 on 2020-11-14 00:53

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0005_auto_20201114_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(default=1, height_field='height', upload_to='images/', verbose_name='Image', width_field='width'),
            preserve_default=False,
        ),
    ]
