# Generated by Django 2.2.6 on 2020-11-14 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0007_photo_ppoi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='ppoi',
        ),
    ]
