# Generated by Django 2.2.6 on 2020-11-15 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0009_auto_20201115_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
