# Generated by Django 2.2.6 on 2020-11-15 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0010_photo_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='source',
        ),
        migrations.AddField(
            model_name='photo',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
