# Generated by Django 2.2.6 on 2020-11-17 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0013_pointofinterest'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointofinterest',
            name='species',
            field=models.ManyToManyField(to='catalogue.Species'),
        ),
    ]
