# Generated by Django 2.2.6 on 2020-11-17 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0015_auto_20201117_2256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='species',
        ),
        migrations.AddField(
            model_name='location',
            name='species',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='catalogue.Species'),
            preserve_default=False,
        ),
    ]
