# Generated by Django 2.2.6 on 2020-11-17 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0016_auto_20201117_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='species',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogue.Species'),
        ),
    ]
