# Generated by Django 2.2.6 on 2020-11-17 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0017_auto_20201117_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='species',
            field=models.ForeignKey(default=46, on_delete=django.db.models.deletion.CASCADE, to='catalogue.Species'),
            preserve_default=False,
        ),
    ]
