# Generated by Django 2.2.6 on 2020-11-19 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('catalogue', '0018_auto_20201117_2358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='species',
        ),
        migrations.RemoveField(
            model_name='speciesinstance',
            name='imprint',
        ),
        migrations.AddField(
            model_name='photo',
            name='content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photo',
            name='object_id',
            field=models.PositiveIntegerField(default=45),
            preserve_default=False,
        ),
    ]
