# Generated by Django 2.2.6 on 2020-11-19 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0019_auto_20201119_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='speciesdescription',
            name='descript_group',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
