# Generated by Django 2.2.6 on 2020-11-19 23:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0020_speciesdescription_descript_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this source', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('seed_count', models.IntegerField()),
                ('source', models.CharField(max_length=100)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('supplier_reference', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='speciesinstance',
            options={'ordering': ['date_sown']},
        ),
        migrations.RenameField(
            model_name='speciesinstance',
            old_name='date_acquired',
            new_name='date_sown',
        ),
        migrations.AddField(
            model_name='speciesinstance',
            name='sowing_method',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='speciesinstance',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogue.Source'),
        ),
    ]
