# Generated by Django 2.2.6 on 2020-11-20 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0021_auto_20201119_2355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='source',
            old_name='source',
            new_name='obtained_from',
        ),
        migrations.RemoveField(
            model_name='speciesinstance',
            name='species',
        ),
        migrations.AddField(
            model_name='source',
            name='species',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='catalogue.Species'),
        ),
    ]
