# Generated by Django 2.2.6 on 2020-11-22 15:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0026_auto_20201122_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
