# Generated by Django 2.2.6 on 2020-11-22 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0028_auto_20201122_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='uuid',
            field=models.UUIDField(editable=False, unique=True),
        ),
    ]
