# Generated by Django 2.2.6 on 2020-11-22 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0029_auto_20201122_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='species',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sources', to='catalogue.Species'),
        ),
    ]
