# Generated by Django 2.2.6 on 2020-11-23 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0031_auto_20201123_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SOWN', 'Sown'), ('ACTIVE', 'Active'), ('NO_RESULTS', 'No results')], default='PENDING', max_length=20),
        ),
    ]
