# Generated by Django 2.2.6 on 2020-12-22 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0033_auto_20201217_2304'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoggerData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=100)),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
