# Generated by Django 3.2.6 on 2021-09-18 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0036_auto_20210912_1540'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='source',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='source',
            name='soil_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sources', to='catalogue.soiltype'),
        ),
        migrations.DeleteModel(
            name='Sowing',
        ),
    ]
